# Generated by Django 5.1.3 on 2024-11-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_payment_method"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Платеж", "verbose_name_plural": "Платежи"},
        ),
    ]
