# Generated by Django 5.1.3 on 2024-12-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payment_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="link_to_payment",
            new_name="link",
        ),
    ]
